feat(cloudfront): add scripts and configuration for tenant invalidation

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,13 +23,19 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        site:
-          - garygerber.com
-          - guidogerbpublishing.com
-          - picklecheeze.com
-          - stream4cloud.com
-          - this-is-my-story.org
-          - ggp.llc
+        include:
+          - site: garygerber.com
+            distId: dt_32sgGiqYklJBVctStUNgG7Yr5C0
+          - site: guidogerbpublishing.com
+            distId: dt_32sg7ajzut8PQfojAV9nIyZSxUX
+          - site: picklecheeze.com
+            distId: dt_32sgNs4ZTHZ6Q5yQtBTZa0AFzfC
+          - site: stream4cloud.com
+            distId: dt_32sgTjXmvRixVhwcvqFpN5YdWSi
+          - site: this-is-my-story.org
+            distId: dt_32sgZgqtD6aKSFyNGcbnPabA9U0
+          - site: ggp.llc
+            distId: dt_32t4XvXr82ATjst1gWnCBS2MlqL
     env:
       NPMRC_TOKEN: ${{ secrets.NPMRC_TOKEN }}
     steps:
@@ -147,18 +153,15 @@ jobs:
           aws-region: ${{ env.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
           role-session-name: github-actions-deploy
-#      - name: Create CloudFront invalidation
-#        shell: bash
-#        env:
-#          DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_MAIN }}
-#          PREFIX: ${{ steps.targets.outputs.prefix }}
-#        run: |
-#          set -euo pipefail
-#
-#          paths='/*'
-#          if [[ -n "$PREFIX" ]]; then
-#            paths="/$PREFIX/*"
-#          fi
-#
-#          echo "Creating CloudFront invalidation on $DISTRIBUTION_ID for paths: $paths"
-#          aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "$paths"
+
+      - name: Create CloudFront Distribution Tenant invalidation
+        shell: bash
+        env:
+          DISTRIBUTION_TENANT_ID: ${{ matrix.distId }}
+        run: |
+          set -euo pipefail
+          JSON='{"Paths":{"Quantity":1,"Items":["/*"]},"CallerReference":"invalidation-test"}'
+          echo "Creating CloudFront Distribution Tenant invalidation on tenant ${DISTRIBUTION_TENANT_ID}"
+          aws cloudfront create-invalidation-for-distribution-tenant \
+            --id "${DISTRIBUTION_TENANT_ID}" \
+            --invalidation-batch "${JSON}"
